package br.com.marhasoft.integrationhub.modules.frotas.validation;

public enum VeiculoValidationCode {

    PLACA_OBRIGATORIA,

    ANO_MODELO_OBRIGATORIO,

    RENAVAM_OBRIGATORIO,

    MODELO_OBRIGATORIO,

    TIPO_FROTA_OBRIGATORIO,

    TIPO_FROTA_INVALIDO,

    PROPRIETARIO_OBRIGATORIO,

    VEICULO_DUPLICIDADE_NAO_PERMITIDA,

    VEICULO_PROPRIETARIO_LOCADOR_MUDANCA,

    VEICULO_PROPRIO_CNPJ_UNIDADE_GESTORA,

    VEICULO_PROPRIETARIO_CADASTRADO,

    VEICULO_LOCADOR_CADASTRADO

}
