package br.com.marhasoft.integrationhub.modules.contabilidade.atualizacaoorcamentaria.validation;

public enum AtualizacaoOrcamentariaValidationCode {

    ATUALIZACAO_ORCAMENTARIA_DUPLICIDADE_NAO_PERMITIDA,

    ATUALIZACAO_ORCAMENTARIA_UNIDADE_GESTORA_MUNICIPIO,

    ATUALIZACAO_ORCAMENTARIA_RESPONSABILIDADE_PROTOCOLO,

    ATUALIZACAO_ORCAMENTARIA_UNIDADE_ORCAMENTARIA_CADASTRADA,

    ATUALIZACAO_ORCAMENTARIA_PROGRAMA_CADASTRADO,

    ATUALIZACAO_ORCAMENTARIA_ACAO_CADASTRADA,

    ATUALIZACAO_ORCAMENTARIA_FUNCAO_STN,

    ATUALIZACAO_ORCAMENTARIA_SUBFUNCAO_STN,

    ATUALIZACAO_ORCAMENTARIA_CATEGORIA_ECONOMICA_STN,

    ATUALIZACAO_ORCAMENTARIA_NATUREZA_DESPESA_STN,

    ATUALIZACAO_ORCAMENTARIA_ELEMENTO_DESPESA_STN,

    ATUALIZACAO_ORCAMENTARIA_FONTE_RECURSO_STN,

    ATUALIZACAO_ORCAMENTARIA_SUPLEMENTACAO_ANULACAO,

    ATUALIZACAO_ORCAMENTARIA_TIPO_14_15,

    ATUALIZACAO_ORCAMENTARIA_DECRETO_OFICIO_OBRIGATORIO,

    ATUALIZACAO_ORCAMENTARIA_TIPO_6_7_8_9_16_DOTACAO_INEXISTENTE,

    ATUALIZACAO_ORCAMENTARIA_TIPO_2,

    ATUALIZACAO_ORCAMENTARIA_TIPO_10,

    ATUALIZACAO_ORCAMENTARIA_TIPO_7_16_EXERCICIO_FONTE,

    ATUALIZACAO_ORCAMENTARIA_TIPO_6_8_9_EXERCICIO_FONTE,

    ATUALIZACAO_ORCAMENTARIA_TIPO_REQUER_DOTACAO_EXISTIR,

    ATUALIZACAO_ORCAMENTARIA_TIPO_15_DOTACAO,

    ATUALIZACAO_ORCAMENTARIA_TIPO_13_DOTACAO,

    ATUALIZACAO_ORCAMENTARIA_TIPO_11_SOMA_SUPLEMENTACAO,

    ATUALIZACAO_ORCAMENTARIA_DECRETO_TIPO_4_8_NAO_PERMITIDO,

    ATUALIZACAO_ORCAMENTARIA_DECRETO_TIPOS_INCOMPATIVEIS,

    ATUALIZACAO_ORCAMENTARIA_OFICIO_TIPO_OBRIGATORIO,

    ATUALIZACAO_ORCAMENTARIA_TIPO_ALTERACAO_VALIDO
}
