spring:
  application:
    name: integration-hub

  datasource:
    url: jdbc:postgresql://localhost:5432/integrationhub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

logging:
  level:
    root: INFO
    br.com.marhasoft: DEBUG

integrationhub:
  sagres:
    base-url: https://api-sagrescaptura-hml.tce.pb.gov.br

marhasoft:
  oauth:
    enabled: true
    server-url: https://login-teste.tce.pb.gov.br
    default-client: teste
    clients:
      teste:
        id: ""
        secret:
      teste1:
        id: ""
        secret:
#        id: ""
#        secret:

      teste2:
        id: tata
        secret: