package br.com.marhasoft.integrationhub.modules.contabilidade.receitaorcamentaria.validation;

public enum ReceitaOrcamentariaValidationCode {

    RECEITA_ORCAMENTARIA_DUPLICIDADE_NAO_PERMITIDA,
    RECEITA_ORCAMENTARIA_TIPO_LANCAMENTO_VALIDO,
    RECEITA_ORCAMENTARIA_TIPO_VALIDO,
    RECEITA_ORCAMENTARIA_CODIGO_RECEITA_ORCAMENTARIA_VALIDO,
    RECEITA_ORCAMENTARIA_CODIGO_FONTE_RECURSO_VALIDO,
    RECEITA_ORCAMENTARIA_CODIGO_CO_VALIDO,
    RECEITA_ORCAMENTARIA_CONTA_BANCARIA_NAO_CADASTRADA,
    RECEITA_ORCAMENTARIA_EXERCICIO_FONTE_RECURSO_VALIDO
}
